### PR TITLE
fix(httpclientpool): rebuild malformed Location URL

### LINKED ISSUE #5900: [BUG] Follow redirect doesn’t URL encode Location header whitespaces.
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

When a Location header contains spaces in between paths/parameters, the follow redirect process does not encode these spaces, causing the request to fail with a 400 Bad Request error from server.

### Expected Behavior

The expectation is that spaces should be URL-encoded (e.g., converted to %20).

### Steps To Reproduce

1. Create a PHP script (test.php) with the following content:
```
<?php
header("Location: https://google.com/?aa bbb");
```
3. Run it `php -S 0.0.0.0:8085 test.php` and open `http://0.0.0.0:8085` notice redirection happens to `https://www.google.com/?aa%20bbb=`
4. Run the following nuclei template with this command `nuclei -t testcase.yaml -u http://0.0.0.0:8085 -debug -fr`:
```yaml
id: template-id
info:
  name: Template Name
  author: pdteam
  severity: info
  description: description
  reference:
    - https://
  tags: tags

http:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}

```

### Expected Result:
Redirection to `https://google.com/?aa%20bbb`

### Actual Result:
The Location header value is not URL-encoded, and the request is redirected as:
`https://google.com/?aa bbb`
This causes a 400 Bad Request error from server due to unencoded spaces.

### Relevant log output

```shell
Debug Data:


GET / HTTP/1.1
Host: 0.0.0.0:8085
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.100 Safari/537.36
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US;q=0.9,en;q=0.8
Cache-Control: max-age=0
Connection: close

[DBG] [template-id] Dumped HTTP response http://0.0.0.0:8085

HTTP/1.0 400 Bad Request
Connection: close
Content-Length: 1555
Content-Type: text/html; charset=UTF-8
Date: Wed, 11 Dec 2024 10:54:13 GMT
Referrer-Policy: no-referrer

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>
[DBG] [template-id] Dumped HTTP response http://0.0.0.0:8085

HTTP/1.1 302 Found
Connection: close
Content-Type: text/html; charset=UTF-8
Date: Wed, 11 Dec 2024 10:54:13 GMT
Host: 0.0.0.0:8085
Location: https://google.com/?aa bbb
X-Powered-By: PHP/8.3.14
```

### Environment

```markdown
- OS: macOS Sonoma (darwin/amd64)
- Nuclei: v3.3.5
- Go: go1.21.0
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dwisiswant0**
## Proposed changes

Fix #5900 

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Summary by CodeRabbit

- **New Features**
	- Introduced a function to check if URLs are properly encoded.
	- Added a new error variable for handling URL reconstruction failures.

- **Bug Fixes**
	- Enhanced logic for managing redirects and rebuilding request URLs.

### CODE REVIEW

File: pkg/protocols/http/httpclientpool/clientpool.go [hunk 1]
```diff
@@ -388,5 +390,29 @@ func checkMaxRedirects(_ *http.Request, via []*http.Request, maxRedirects int) e
...
+
+		req.URL = parsed.URL
+	}
+
 	return nil
 }
+
+// isURLEncoded is an helper function to check if the URL is already encoded
+//
+// NOTE(dwisiswant0): shall we move this under `projectdiscovery/utils/urlutil`?
```
Comment (dogancanbakir) [inline pkg/protocols/http/httpclientpool/clientpool.go:409]: ++

**Review by dogancanbakir — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]

**Review by Ice3man543 — APPROVED** [review]
