### PR TITLE
Issue 2840 aws signature

### LINKED ISSUE #2840: AWS Templates with wrong signature
### Nuclei version:
2.7.9

### Current Behavior:
Amazon endpoint rejects signed AWS request due to missing/wrong info

### Expected Behavior:
Amazon accepting AWS signature

### Steps To Reproduce:
AWS signed template:
```yaml
id: sts-get-caller-identity
info:
  name: STS get-caller-identity
  author: princechaddha
  severity: info

self-contained: true
signature: aws

requests:
  - raw:
      - |
        POST https://sts.us-east-1.amazonaws.com/ HTTP/1.1
        Host: sts.us-east-1.amazonaws.com
        Content-Type: application/x-www-form-urlencoded; charset=utf-8
        User-Agent: aws-cli/2.1.28 Python/3.8.8 Darwin/21.6.0 exe/x86_64 prompt/off command/sts.get-caller-identity
        Content-Length: 43

        Action=GetCallerIdentity&Version=2011-06-15

    matchers:
      - type: word
        words:
          - "<GetCallerIdentityResult>"

      - type: status
        status:
          - 200
```

Run the following command:

```console
$ go run . -V "aws-id=xxx" -V "aws-secret=yyyy" -V "service=zzzz" -V "region=pppp"
```

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
## Proposed changes

1. Fix AWS HTTP Request Signer 
2. Use `aws-go-sdk-2` instead of `aws-go-sdk` for following reasons
    1.  Readily Available `SignHTTP` method instead of manually crafting it
    2. Supports go modules (> 1.13) . ( `aws-go-sdk` was not modular and was based on go <1.13)
    3.  Performance improvements etc. 
3. Implementation Changes ( Now uses `context.context` to pass values instead of interfaces )

closes #2840

### CODE REVIEW

File: v2/pkg/protocols/http/signer/aws-sign.go [hunk 1]
```diff
@@ -0,0 +1,137 @@
...
+		return err
+	}
+
+	// Bug Request has content-length but no body
+	rbody, _ := io.ReadAll(request.Body)
+	request.Body.Close()
+	request.Body = io.NopCloser(bytes.NewBuffer(rbody))
+	fmt.Printf("request body is :\n*=\n%v\n=*\n", string(rbody))
+	//
+
```
Comment (tarunKoyalwar) [inline v2/pkg/protocols/http/signer/aws-sign.go:66]: @Mzack9999 

Request passed to `SignHTTP` function is malformed which is core problem for malformed signatures
content length is available but body is empty . However `debug`request shown is correct and is different from what was passed to `SignHTTP` .  

Possible Explaination `might be related to ( generated.Request -> http.Request )`

This can be verified by running Unit Test in `signer` package where request is created using `http.request` and it executes successfully.

Comment (tarunKoyalwar) [reply v2/pkg/protocols/http/signer/aws-sign.go:66]: Above code is only used to Validate the bug

**Comment by tarunKoyalwar** [comment]
Template File

```yml
id: sts-get-caller-identity

info:
  name: STS get-caller-identity
  author: princechaddha
  severity: info
  
self-contained: true
signature: aws

requests:
  - raw:
      - |
        POST https://sts.amazonaws.com/ HTTP/1.1
        Host: sts.amazonaws.com
        Content-Type: application/x-www-form-urlencoded; charset=utf-8
        User-Agent: aws-cli/2.9.1 Python/3.11.0 Darwin/22.1.0 source/arm64 prompt/off command/sts.get-caller-identity

        Action=GetCallerIdentity&Version=2011-06-15

    matchers:
      - type: word
        words:
          - "<GetCallerIdentityResult>"

      - type: status
        status:
          - 200%      
```

**Comment by tarunKoyalwar** [comment]
## Run Below Command to  Validate

```sh
go run . -t aws-sts-template.yaml -V "service=sts" -V "region=us-east-1" -debug
```

Note:
creds will be picked up from $HOME/.aws or Enviornment variables  no need to pass manually

File: v2/pkg/protocols/http/signer/aws-sign.go [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+	}
+	if err := a.options.Validate(); err != nil {
+		return err
+	}
+
+	// Bug Request has content-length but no body
+	rbody, _ := io.ReadAll(request.Body)
+	request.Body.Close()
+	request.Body = io.NopCloser(bytes.NewBuffer(rbody))
+	fmt.Printf("request body is :\n*=\n%v\n=*\n", string(rbody))
```
[the remark this answers is not in the document]
Comment (tarunKoyalwar) [reply v2/pkg/protocols/http/signer/aws-sign.go:64]: False Positive . This piece of code is only used to validate/debug actual bug and will be removed

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
- [x] Merge conflicts
- [ ] Ready for review or still draft?

**Comment by tarunKoyalwar** [comment]
@Mzack9999  it is still in draft .
As described here https://github.com/projectdiscovery/nuclei/pull/2924#discussion_r1034428650 .
Individual component (i.e unit test) is working but it is failing when integrated with nuclei

**Comment by tarunKoyalwar** [comment]
Issue inherited from `retryablehttp-go`  i.e https://github.com/projectdiscovery/retryablehttp-go/issues/32
request body was not available because original request was consumed by `retryablehttp-go` 
will be fixed by  https://github.com/projectdiscovery/retryablehttp-go/pull/33

cc @Mzack9999

**Comment by tarunKoyalwar** [comment]
```sh
 go run . -t ~/Codebase/aws-sts-template.yaml -V "service=sts" -V "region=us-east-1" -stats

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   2.7.9

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions.
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] nuclei-templates are not installed, installing...
[INF] Successfully downloaded nuclei-templates (v9.2.9) to /Users/tarun/nuclei-templates. GoodLuck!
[INF] Using Nuclei Engine 2.7.9 (latest)
[INF] Using Nuclei Templates 9.2.9 (latest)
[INF] Templates added in last update: 45
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 0
[2022-12-02 15:17:19] [sts-get-caller-identity] [http] [info] https://sts.amazonaws.com/
[0:00:01] | Templates: 1 | Hosts: 0 | RPS: 0 | Matched: 1 | Errors: 0 | Requests: 1/0 (18446744073709551615%)
```

**Review by Mzack9999 — APPROVED** [review]
lgtm! - cc @princechaddha

**Review by ehsandeep — APPROVED** [review]
```console
go run . -V "service=sts" -V "region=us-east-1" -t test.yaml  -silent

[sts-get-caller-identity] [http] [info] https://sts.amazonaws.com/
```
