### PR TITLE
add `-dast` flag and multiple bug fixes for dast templates

### LINKED ISSUE #4929: Non-printable characters in extractor output are inconsistently escaped
Starting from version 3.2.0, only the new line (alias \n, LF, 0x0A) character is excaped in the output of the extractors.
This can cause issues, for example if the extracted data is in CRLF line ending format, then only the LF (Line-Feed = \n) is escaped, leaving the CR (Carriage-Return) character messes up the output.

### Nuclei version:
3.2.0 - 3.2.2

### Current Behavior:
```
./v3.2.0_nuclei -disable-update-check -u https://httpbin.org/user-agent -t test.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

                projectdiscovery.io

[INF] Current nuclei version: v3.2.2 (outdated)
[INF] Current nuclei-templates version:  (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 0
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
\n{\n  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"\n}]
```

### Previous Behavior:
```
./v3.1.10_nuclei -disable-update-check -u https://httpbin.org/user-agent -t test.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.1.10

                projectdiscovery.io

[INF] Current nuclei version: v3.1.10 (outdated)
[INF] Current nuclei-templates version:  (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 0
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[test] [http] [info] https://httpbin.org/user-agent ["HTTP/1.1 200 OK\r\nConnection: close\r\nContent-Length: 152\r\nAccess-Control-Allow-Credentials: true\r\nAccess-Control-Allow-Origin: *\r\nContent-Type: application/json\r\nDate: Thu, 21 Mar 2024 15:25:31 GMT\r\nServer: gunicorn/19.9.0\r\n\r\n{\n  \"user-agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63\"\n}"]
```

### Steps To Reproduce:
The template I used for testing:
```
id: test
info:
  name: Test
  author: Levente Kovats
  severity: info
http:
  - method: GET
    path:
      - "{{BaseURL}}"
    matchers:
      - type: dsl
        dsl:
          - true
    extractors:
      - type: dsl
        dsl:
          - response
```

If I redirect the output to a file, and open it with a simple text editor, it looks like this:
image
It is clearly showing that the LF character is excaped (to \n), but the CR is not, and that takes back the console carriage to the begining of the line, without starting a new line, which leads to overwriting the previous line of the data.

### Anything else:
I guess it is introduced in PR [#4849](https://github.com/projectdiscovery/nuclei/pull/4849/files#diff-80c57a0675312f503dd698285e99e84be3c5cfbbfd4f275d5e106e08fd4e2eb1L63-R63) from issue https://github.com/projectdiscovery/nuclei/issues/4841 

It's not clear to me, what was the reason behind not escaping all the non-ASCII / non-printable characters any more?

### LINKED ISSUE #4935: filter support to dast templates
Follow up for https://github.com/projectdiscovery/nuclei/pull/4925

- [x] support for filters for old dast templates ( missing value of method variable )

```yaml
variables:
  first: "cookie_injection"

http:
  - filters:
      - type: dsl
        dsl:
          - 'method == "GET"'
        condition: and

    payloads:
      reflection:
        - "{{first}}"

    fuzzing:
      - part: query
        type: postfix
        fuzz:
          - "{{reflection}}"

    matchers:
      - type: regex
        part: header
        regex:
          - '(?m)(?i)(^set-cookie.*cookie_injection.*)'
 ```
 - [x] improve `-dast` (fuzz) option to load only dast based templates

### LINKED ISSUE #4946: interactsh-url dependent variables are not lazy evaluated
### Nuclei version:

main | latest

### Current Behavior:

```yaml
id: some-exploit

info:
  name: "Some Exploit"
  author: pdteam
  severity: critical
  description: this is a test description

variables:
  callback: "{{interactsh-url}}"
  cmd: "nslookup {{callback}}"
  payload: '{{base64(cmd)}}'

http:
  - raw:
      - |
        GET /{{payload}} HTTP/1.1
        Host: {{Hostname}}
    
    matchers:
      - type: status
        status:
          - 200

    extractors:
      - type: dsl
        dsl:
          - 'base64_decode(payload)'
```

```console
$ nuclei -u https://scanme.sh -t a.yaml       

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

		projectdiscovery.io

[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 85
[INF] Templates loaded for current scan: 1
[WRN] Loaded 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Using Interactsh Server: oast.fun
[some-exploit] [http] [critical] https://scanme.sh/bnNsb29rdXAge3tpbnRlcmFjdHNoLXVybH19 [nslookup {{interactsh-url}}]
```

### Expected Behavior:

```console
$ ./nuclei -u https://scanme.sh -t a.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

		projectdiscovery.io

[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 85
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Using Interactsh Server: oast.online
[some-exploit] [http] [critical] https://scanme.sh/bnNsb29rdXAgY28xZGtmc280N21oOGNwOGg1MTA2ODRyb2NtNHE5dWd5Lm9hc3Qub25saW5l ["nslookup co1dkfso47mh8cp8h510684rocm4q9ugy.oast.online"]
```

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
## Proposed Changes

- add `-dast` flag and deprecate `-fuzz` flag 
- fuzz: add default get method in fuzzing filters
- fuzz: remove residual payload logic from old implementation
- fuzz: fix `no values to generate requests` error
- improve stdout template loading stats
- stdout: force display warnings if no templates are loaded
- closes #4935 
- closes #4946 
- closes #4929 

### Before 
- when running dast template with multiple mode, payloads were stacked after every run instead of being reset 
```console
$  nuclei -l integration_tests/fuzz/testData/ginandjuice.proxify.yaml -im yaml -t b.yaml -fuzz -v         130 ↵

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 85
[INF] Templates loaded for current scan: 1
[WRN] Loaded 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 9
[VER] [fuzz0test] Sent HTTP request to http://127.0.0.1:8082/blog/post?postId=3%27&source=proxify%27
[VER] [fuzz0test] Sent HTTP request to http://127.0.0.1:8082/blog/post?postId=3%27%22&source=proxify%27%22
[VER] [fuzz0test] Sent HTTP request to http://127.0.0.1:8082/blog/post?postId=3%27%22%3B&source=proxify%27%22%3B
[INF] No results found. Better luck next time!
```

### After
```console
$  ./nuclei -l integration_tests/fuzz/testData/ginandjuice.proxify.yaml -im yaml -t b.yaml -dast -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 85
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 9
[VER] [fuzz0test] Sent HTTP request to http://127.0.0.1:8082/blog/post?postId=3'&source=proxify'
[VER] [fuzz0test] Sent HTTP request to http://127.0.0.1:8082/blog/post?postId=3"&source=proxify"
[VER] [fuzz0test] Sent HTTP request to http://127.0.0.1:8082/blog/post?postId=3;&source=proxify;
[INF] No results found. Better luck next time!
```

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
- closes #4929 without breaking json extracted output

```console
$ ./nuclei -t a.yaml -u scanme.sh

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

		projectdiscovery.io

[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 85
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[ssh-server-enumeration] [javascript] [info] scanme.sh:22 ["{"AlgorithmSelection":{"client_to_server_alg_group":{"cipher":"aes128-ctr","compression":"none","mac":"hmac-sha2-256"},"dh_kex_algorithm":"curve25519-sha256@libssh.org","host_key_algorithm":"ecdsa-sha2-nistp256","server_to_client_alg_group":{"cipher":"aes128-ctr","compression":"none","mac":"hmac-sha2-256"}},"Banner":"","ClientID":null,"ClientKex":null,"Crypto":null,"DHKeyExchange":{"curve25519_sha256_params":{"server_public":"JksLByu2//6pnjcij46E6ovX9XzUkE7Xu6Ctnax8HkI="},"server_host_key":{"algorithm":"ecdsa-sha2-nistp256","ecdsa_public_key":{"b":"WsY12Ko6k+ez671VdpiGvGUdBrDMU7D2O848PifSYEs=","curve":"P-256","gx":"axfR8uEsQkf4vOblY6RA8ncDfYEt6zOg9KE5RdiYwpY=","gy":"T+NC4v4af5uO5+tKfA+eFivOM1drMV7Oy7ZAaDe/UfU=","length":256,"n":"/////wAAAAD//////////7zm+q2nF56E87nKwvxjJVE=","p":"/////wAAAAEAAAAAAAAAAAAAAAD///////////////8=","x":"z26Q0tpPfVKxgLHzuj0SxaECCYLqlIm5tNy3Fz5KsUw=","y":"tjGcTXlRlQy67VjJLj5iqO3X+VvGEFw2bkRSSsHHrCg="},"fingerprint_sha256":"28cdf69e089470409de139506f5f33fdcc5b747641d974da3236863aa8a98ca5","raw":"AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBM9ukNLaT31SsYCx87o9EsWhAgmC6pSJubTctxc+SrFMtjGcTXlRlQy67VjJLj5iqO3X+VvGEFw2bkRSSsHHrCg="},"server_signature":{"h":"mk0WH/upBHoC+NJqYA9Fj+Yu/VouaibNJfP/B4Q1ADI=","parsed":{"algorithm":"ecdsa-sha2-nistp256","value":"AAAAIQDVxji4Wi9YYmzQQfOc/c/+msf7zzGKMGeBYOPpklQXVgAAACBzzmpcB0y1u9tePWvC1Y/BJ9qF65l38tbwNvvJhc2BUw=="},"raw":"AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAABJAAAAIQDVxji4Wi9YYmzQQfOc/c/+msf7zzGKMGeBYOPpklQXVgAAACBzzmpcB0y1u9tePWvC1Y/BJ9qF65l38tbwNvvJhc2BUw=="}},"ServerID":{"Comment":"Ubuntu-4ubuntu0.11","ProtoVersion":"2.0","Raw":"SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.11","SoftwareVersion":"OpenSSH_8.2p1"},"ServerKex":{"client_to_server_ciphers":["chacha20-poly1305@openssh.com","aes128-ctr","aes192-ctr","aes256-ctr","aes128-gcm@openssh.com","aes256-gcm@openssh.com"],"client_to_server_compression":["none","zlib@openssh.com"],"client_to_server_macs":["umac-64-etm@openssh.com","umac-128-etm@openssh.com","hmac-sha2-256-etm@openssh.com","hmac-sha2-512-etm@openssh.com","hmac-sha1-etm@openssh.com","umac-64@openssh.com","umac-128@openssh.com","hmac-sha2-256","hmac-sha2-512","hmac-sha1"],"cookie":"1MCxZqbogvRN/wo7mhuUow==","first_kex_follows":false,"host_key_algorithms":["rsa-sha2-512","rsa-sha2-256","ssh-rsa","ecdsa-sha2-nistp256","ssh-ed25519"],"kex_algorithms":["curve25519-sha256","curve25519-sha256@libssh.org","ecdh-sha2-nistp256","ecdh-sha2-nistp384","ecdh-sha2-nistp521","diffie-hellman-group-exchange-sha256","diffie-hellman-group16-sha512","diffie-hellman-group18-sha512","diffie-hellman-group14-sha256","kex-strict-s-v00@openssh.com"],"reserved":0,"server_to_client_ciphers":["chacha20-poly1305@openssh.com","aes128-ctr","aes192-ctr","aes256-ctr","aes128-gcm@openssh.com","aes256-gcm@openssh.com"],"server_to_client_compression":["none","zlib@openssh.com"],"server_to_client_macs":["umac-64-etm@openssh.com","umac-128-etm@openssh.com","hmac-sha2-256-etm@openssh.com","hmac-sha2-512-etm@openssh.com","hmac-sha1-etm@openssh.com","umac-64@openssh.com","umac-128@openssh.com","hmac-sha2-256","hmac-sha2-512","hmac-sha1"]},"UserAuth":["publickey","password"]}"]
```

**Comment by tarunKoyalwar** [comment]
- aws request signature templates can only be run in signed & verified templates
```console
$ ./nuclei -t ~/Codebase/nuclei-templates/http/cloud/aws                                             

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

		projectdiscovery.io

[WRN] Found 9 templates loaded with deprecated protocol syntax, update before v3 for continued support.
[WRN] Skipping 25 templates, HTTP Request signatures can only be used in Signed & Verified templates.
[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] No results found. Better luck next time!
[FTL] Could not run nuclei: no templates provided for scan
```

File: pkg/catalog/loader/loader.go [hunk 1]
```diff
@@ -405,41 +403,53 @@ func (store *Store) LoadTemplatesWithTags(templatesList, tags []string) []*templ
...
+					stats.Increment(templates.SkippedRequestSignatureStats)
+					continue
+				}
+				// DAST only templates
+				if store.config.ExecutorOptions.Options.DAST {
+					// check if the template is a DAST template
+					if parsed.IsFuzzing() {
+						loadedTemplates = append(loadedTemplates, parsed)
+					} else {
+						_ = parsed
```
Comment (Mzack9999) [inline pkg/catalog/loader/loader.go:417]: I guess this can be removed? (there is another one at https://github.com/projectdiscovery/nuclei/blob/0d6cff2165569e6151bd05a3a0b65acd77c77e9f/pkg/protocols/http/raw/raw.go#L286

File: pkg/fuzz/component/path.go [hunk 2]
```diff
@@ -83,3 +83,11 @@ func (q *Path) Rebuild() (*retryablehttp.Request, error) {
 	}
 	return cloned, nil
 }
+
+// Clones current state to a new component
+func (q *Path) Clone() Component {
+	return &Path{
+		value: q.value.Clone(),
+		req:   q.req,
```
Comment (Mzack9999) [inline pkg/fuzz/component/path.go:91]: I guess that if we are fuzzing the same request we would need a clone here as well?

File: pkg/fuzz/dataformat/kv.go [hunk 3]
```diff
@@ -14,6 +16,21 @@ type KV struct {
 	OrderedMap *mapsutil.OrderedMap[string, any]
 }
 
+// Clones the current state of the KV struct
+func (kv *KV) Clone() KV {
+	newKV := KV{}
+	if kv.OrderedMap == nil {
+		newKV.Map = make(map[string]interface{})
```
Comment (Mzack9999) [inline pkg/fuzz/dataformat/kv.go:23]: what about `newKV.Map = maps.Clone(kv.Map)`?

File: pkg/fuzz/parts.go [hunk 4]
```diff
@@ -34,19 +34,21 @@ func (rule *Rule) checkRuleApplicableOnComponent(component component.Component)
...
-		return rule.executePartComponentOnValues(input, payload.Value, ruleComponent)
+		return rule.executePartComponentOnValues(input, payload.Value, ruleComponent.Clone())
 	}
 }
 
 // executePartComponentOnValues executes this rule on a given component and payload
 // this supports both single and multiple [ruleType] modes
 // i.e if component has multiple values, they can be replaced once or all depending on mode
 func (rule *Rule) executePartComponentOnValues(input *ExecuteRuleInput, payloadStr string, ruleComponent component.Component) error {
+
```
Comment (Mzack9999) [inline pkg/fuzz/parts.go:51]: empty line

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
minor suggestions

**Comment by tarunKoyalwar** [comment]
## Fix lazy eval of `interactsh-url` (see: https://github.com/projectdiscovery/nuclei/issues/4946)

```console
$ ./nuclei -u https://scanme.sh -t a.yaml

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.2.2

		projectdiscovery.io

[INF] Current nuclei version: v3.2.2 (latest)
[INF] Current nuclei-templates version: v9.8.0 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 85
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[INF] Using Interactsh Server: oast.online
[some-exploit] [http] [critical] https://scanme.sh/bnNsb29rdXAgY28xZGtmc280N21oOGNwOGg1MTA2ODRyb2NtNHE5dWd5Lm9hc3Qub25saW5l ["nslookup co1dkfso47mh8cp8h510684rocm4q9ugy.oast.online"]
```

File: pkg/fuzz/component/path.go (hunk 2 above)
Comment (tarunKoyalwar) [reply pkg/fuzz/component/path.go:91]: yup , missed that one

**Review by Mzack9999 — APPROVED** [review]
lgtm - Might be worth considering the implementation in a follow up task of a HTTP proxy mode for RFC-compliant requests, so that DAST mode can be performed on in-flight requests transparently and nuclei could virtually support all third party apps supporting proxy, without the need of various intermediate formats like openapi

**Comment by tarunKoyalwar** [comment]
follow-up https://github.com/projectdiscovery/nuclei/issues/4953

**Review by ehsandeep — APPROVED** [review]

**Comment by ansanyuan** [comment]
Can this dast engine test post content in http packages? and headers, similar to awvs. Or can we only test the fields in GET at present, and there is little information on the Internet, so let's ask here.THX^^
