### PR TITLE
Fixing atomic bool check

### LINKED ISSUE #3338: `No results found error` when match found with `self-contained` template
### Nuclei version:
v2.8.9

### Current Behavior:
```yaml
[INF] Using Nuclei Engine 2.8.9 (latest)
[INF] Using Nuclei Templates 9.3.7 (latest)
[INF] Templates added in last update: 58
[INF] Templates loaded for scan: 1
[sherlock-username:7cups] [http] [info] https://www.7cups.com/@blue
[INF] No results found. Better luck next time!
```

### Expected Behavior:
```
[INF] Using Nuclei Engine 2.8.9 (latest)
[INF] Using Nuclei Templates 9.3.7 (latest)
[INF] Templates added in last update: 58
[INF] Templates loaded for scan: 1
[sherlock-username:7cups] [http] [info] https://www.7cups.com/@blue
```
### Steps To Reproduce:

```yamll
id: sherlock-username

info:
  name: Sherlock Username Enumeration
  author: DhiyaneshDk
  severity: info
  description: Hunt down social media accounts by username across social networks
  reference:
    - https://github.com/sherlock-project/sherlock
    - https://sherlock-project.github.io/
  tags: token-spray,sherlock,enum,osint

self-contained: true

requests:
  - method: GET
    path:
      - "https://www.7cups.com/@{{username}}"

    matchers:
      - type: word
        part: body
        name: 7cups
        words:
          - 'screenName:'
          - 'userType:'
          - 'userIDe:'
        condition: and
```

```bash
nuclei -var username=blue -t test.yaml
```
-->

### PR DESCRIPTION
**Pull request by Mzack9999**
## Proposed changes
Fixing return value override due to scan strategy result.
Closes #3338 

## Checklist
- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: v2/pkg/core/execute_options.go [hunk 1]
```diff
@@ -60,13 +60,16 @@ func (e *Engine) ExecuteScanWithOpts(templatesList []*templates.Template, target
...
 	switch e.options.ScanStrategy {
 	case "template-spray":
-		results = e.executeTemplateSpray(filtered, target)
+		strategyResult = e.executeTemplateSpray(filtered, target)
 	case "host-spray":
-		results = e.executeHostSpray(filtered, target)
+		strategyResult = e.executeHostSpray(filtered, target)
 	}
 
+	results.CompareAndSwap(false, strategyResult.Load())
```
Comment (tarunKoyalwar) [inline v2/pkg/core/execute_options.go:71]: @Mzack9999 what do you think of adding `default` case to switch case . if someone is using nuclei sdk and scanstrategy is not one them it will panic
due to `strategyResult.Load()`

**Review by tarunKoyalwar — APPROVED** [review]
lgtm! approved with a comment

**Review by ehsandeep — APPROVED** [review]
