### PR TITLE
fix(trackers): paginate gitea to find all issues when searching for duplicates

### LINKED ISSUE #6706: [BUG] Gitea issue tracker fails to find older issues
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

When using the Gitea issue tracker, duplicates of older issues are created.

### Expected Behavior

Issue reporting should correctly find old issues.

### Steps To Reproduce

Configure Gitea as issue tracker, and ensure the tracker has more than 50 unique issues logged. Run Nuclei and find it logs duplicates for older, existing issues.

### Environment

```markdown
- OS: Linux 
- Nuclei: v3.6.1
- Go: go1.25.5
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by leonjza**
## Proposed changes

When searching for duplicates, issue API responses are paginated. Because the reporting integration does not paginate results, older issues are skipped and logged as a duplicate.

Fixes #6706.

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Summary by CodeRabbit

* **Refactor**
  * Improved issue lookup from Gitea repositories to iterate through paginated results for more reliable matching.
  * Added configurable paging controls (page size and max pages) with an early-exit when limits are reached, preserving existing error behavior.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: pkg/reporting/trackers/gitea/gitea.go [hunk 1]
```diff
@@ -151,21 +151,34 @@ func (i *Integration) ShouldFilter(event *output.ResultEvent) bool {
...
 
-	for _, issue := range issueList {
-		if issue.Title == title {
-			return issue, nil
+	for {
+		issueList, _, err := i.client.ListRepoIssues(i.options.ProjectOwner, i.options.ProjectName, opts)
+		if err != nil {
+			return nil, err
 		}
-	}
```
Comment (dwisiswant0) [inline pkg/reporting/trackers/gitea/gitea.go:166]: This looks unbounded. We should cap it to avoid hammering the API and hurting performance.

Comment (leonjza) [reply pkg/reporting/trackers/gitea/gitea.go:166]: Could you be more specific on what you'd like to see over and above the existing length check on `issueList`?

Comment (dwisiswant0) [reply pkg/reporting/trackers/gitea/gitea.go:166]: In repos with tons of issues, this unbounded loop can end up making a lot of API calls and slow things down. The logic works, but maybe adding a configurable max page limit could help keep things under control for huge repos.

Comment (leonjza) [reply pkg/reporting/trackers/gitea/gitea.go:166]: Makes sense! Added some configurable bounds now.
