### PR TITLE
js: generate matcher-status event

### LINKED ISSUE #5449: pre-condition does not create matcher-status event
### Nuclei version:

main | latest

### Current Behavior:

when using pre-condition if its value is false then the matcher-status event is not generated for javascript protocol

### Expected Behavior:

a matcher-status event regardless when it exits

### Steps To Reproduce:

```yaml
id: ssh-server-enumeration

info:
  name: Detect SSH on port 22.
  author: Justin Bacco
  severity: info
  metadata:
    max-request: 2
    shodan-query: port:22
  tags: enum,js,ssh,network

javascript:
  - pre-condition: |
      isPortOpen(Host,Port)
    code: |
      var m = require("nuclei/ssh");
      var c = m.SSHClient();
      var response = c.ConnectSSHInfoMode(Host, Port);
      Export(response);

    args:
      Host: "{{Host}}"
      Port: 22

    matchers:
      - type: dsl
        dsl:
          - "success == true"
```

```console
$ nuclei -u scanme.sh:1234 -t a.yaml -ms -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.0

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.3.0 (latest)
[INF] Current nuclei-templates version: v9.9.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 67
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[WRN] [ssh-server-enumeration] Could not execute request for scanme.sh:1234: [ssh-server-enumeration:RUNTIME] could not execute pre-condition: dial tcp [2400:6180:0:d0::91:1001]:1234: connect: connection refused
[INF] No results found. Better luck next time!

```

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
### Proposed Changes

due to inconsistency earlier javascript protocol pre-condition (false) status did not create failed event even if `matcher-status` is set to true , this is now resolved by creating a failed matcher-status event if pre-condition errored out or return false

- closes #5449 

### Before

```console
$  nuclei -u scanme.sh:1234 -t a.yaml -ms -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.0

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.3.0 (latest)
[INF] Current nuclei-templates version: v9.9.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 67
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[WRN] [ssh-server-enumeration] Could not execute request for scanme.sh:1234: [ssh-server-enumeration:RUNTIME] could not execute pre-condition: dial tcp [2400:6180:0:d0::91:1001]:1234: connect: connection refused
[INF] No results found. Better luck next time!
```

### After

```console
$ ./nuclei -u scanme.sh:1234 -t a.yaml -ms -v

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.3.0

		projectdiscovery.io

[VER] Started metrics server at localhost:9092
[INF] Current nuclei version: v3.3.0 (latest)
[INF] Current nuclei-templates version: v9.9.2 (latest)
[WRN] Scan results upload to cloud is disabled.
[INF] New templates added in latest release: 67
[INF] Templates loaded for current scan: 1
[WRN] Loading 1 unsigned templates for scan. Use with caution.
[INF] Targets loaded for current scan: 1
[WRN] [ssh-server-enumeration] Could not execute request for scanme.sh:1234: dial tcp [2400:6180:0:d0::91:1001]:1234: connect: connection refused
[ssh-server-enumeration] [failed] [javascript] [info] scanme.sh:1234
```

### Template

```yaml
id: ssh-server-enumeration

info:
  name: Detect SSH on port 22.
  author: Justin Bacco
  severity: info
  metadata:
    max-request: 2
    shodan-query: port:22
  tags: enum,js,ssh,network

javascript:
  - pre-condition: |
      isPortOpen(Host,Port)
    code: |
      var m = require("nuclei/ssh");
      var c = m.SSHClient();
      var response = c.ConnectSSHInfoMode(Host, Port);
      Export(response);

    args:
      Host: "{{Host}}"
      Port: 22

    matchers:
      - type: dsl
        dsl:
          - "success == true"
```

### CODE REVIEW

File: pkg/js/compiler/compiler.go [hunk 1]
```diff
@@ -55,6 +55,10 @@ type ExecuteArgs struct {
 	TemplateCtx map[string]interface{} // templateCtx contains template scoped variables
 }
 
+func (e *ExecuteArgs) Map() map[string]interface{} {
```
Comment (dwisiswant0) [inline pkg/js/compiler/compiler.go:58]: Missing doc.

File: pkg/js/compiler/compiler.go [hunk 2]
```diff
@@ -66,12 +70,22 @@ func NewExecuteArgs() *ExecuteArgs {
 // ExecuteResult is the result of executing a script.
 type ExecuteResult map[string]interface{}
 
+func (e ExecuteResult) Map() map[string]interface{} {
```
Comment (dwisiswant0) [inline pkg/js/compiler/compiler.go:73]: Missing doc.

File: pkg/js/global/scripts.go [hunk 3]
```diff
@@ -111,11 +114,16 @@ func initBuiltInFunc(runtime *goja.Runtime) {
...
 			if len(timeout) > 0 {
-				timeoutInSec = timeout[0]
+				var cancel context.CancelFunc
+				ctx, cancel = context.WithTimeout(ctx, time.Duration(timeout[0])*time.Second)
+				defer cancel()
 			}
-			conn, err := net.DialTimeout("tcp", net.JoinHostPort(host, port), time.Duration(timeoutInSec)*time.Second)
+			if host == "" || port == "" {
+				return false, errkit.New("isPortOpen: host or port is empty")
+			}
```
Comment (dwisiswant0) [inline pkg/js/global/scripts.go:125]: DRY with lines 148-150, could be simplified by turning it into a util function.

**Review by dwisiswant0 — CHANGES_REQUESTED** [review]

File: pkg/js/compiler/compiler.go (hunk 2 above)
Comment (tarunKoyalwar) [reply pkg/js/compiler/compiler.go:75]: maybe we need a linter rule 😄

File: pkg/js/global/scripts.go (hunk 3 above)
Comment (tarunKoyalwar) [reply pkg/js/global/scripts.go:125]: not sure tbh, this feels simple enough , in go due to its syntax condition with early exit will always require 2 lines of code, we have a helper function in utils `generics` package and could do something like `generics.EqualsAny("",host,port)` but feels like it will overcomplicate things instead of KISS
let me know if you feel otherwise

File: pkg/js/compiler/compiler.go (hunk 2 above)
Comment (dwisiswant0) [reply pkg/js/compiler/compiler.go:75]: @tarunKoyalwar  - we've already been using `golangci-lint` so we might just need to tweak its config.

**Review by dwisiswant0 — APPROVED** [review]

File: pkg/js/compiler/compiler.go (hunk 2 above)
Comment (tarunKoyalwar) [reply pkg/js/compiler/compiler.go:75]: yes

**Review by ehsandeep — APPROVED** [review]
