### PR TITLE
fix(headless): incorrect last navigated URL

### LINKED ISSUE #6274: [BUG] headless protocol outputs incorrect URL in "matched-at" field for targets with redirects
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

When running nuclei templates leveraging the [headless protocol](https://docs.projectdiscovery.io/templates/protocols/headless), the input URL is reported for the `matched-at` field, even when the input URL redirects to a different location, and the different location is what the templates matches against.

### Expected Behavior

The final URL where the input URL redirects to and the template matches against is reported in the `matched-at` field.

### Steps To Reproduce

1. Find a target that has an HTTP redirect chain
```
curl -Isk -L "http://www.projectdiscovery.io"
HTTP/1.0 308 Permanent Redirect
Content-Type: text/plain
Location: https://www.projectdiscovery.io/
...

HTTP/2 308
content-type: text/plain
location: https://projectdiscovery.io/
...

HTTP/2 200
...
x-powered-by: Next.js, Payload
...
```
2. Run a headless nuclei template against the target
```
nuclei -u "http://www.projectdiscovery.io" -headless -t headless/technologies/js-libraries-detect.yaml -jsonl -omit-raw -silent | jq '."matched-at"'

"http://www.projectdiscovery.io"
```
3. Observe that the 'matched-at' field has the original target URL (`http://www.projectdiscovery.io`), not the final URL that gets redirected to (`https://projectdiscovery.io/`)

### Relevant log output

```shell

```

### Environment

```markdown
- OS: ubuntu 24.04
- Nuclei: v3.2.8
- Go: go1.22.4
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dwisiswant0**
## Proposed changes

Fixes #6274

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Summary by CodeRabbit

- **New Features**
  - Improved tracking of the last navigated URL during page navigation and lifecycle events.
- **Refactor**
  - Streamlined internal map handling for request processing, resulting in more efficient data merging.

### CODE REVIEW

File: pkg/protocols/headless/engine/page.go [hunk 1]
```diff
@@ -197,6 +198,7 @@ func (i *Instance) Run(ctx *contextargs.Context, actions []*Action, payloads map
 	// we assume it's the one matching the initial URL
 	if len(createdPage.History) > 0 {
 		firstItem := createdPage.History[0]
+		// fmt.Printf("firstItem.RawResponse: %v\n", firstItem.RawResponse)
```
Comment (dogancanbakir) [inline pkg/protocols/headless/engine/page.go]: we can remove dead code

Comment (dwisiswant0) [reply pkg/protocols/headless/engine/page.go]:
```suggestion
```
