### PR TITLE
Fix tempalte-id validation

### LINKED ISSUE #5247: Nuclei -validate not flagging invalid ID in template
The Nuclei `-validate` flag is not flagging the invalid ID of the template. The following template is being validated without any error:

```yaml
id: aviatrix detect

info:
  name: Aviatrix Detect
  author: princechaddha
  severity: info
  tags: tech,aviatrix
  description: |
    Detects Aviatrix Controller API misconfigurations
  impact: |
    May lead to unauthorized access or data leakage
  remediation: |
    Review and adjust Aviatrix Controller API configurations to ensure proper access controls

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers-condition: and
    matchers:

      - type: word
        part: body
        words:
          - "<title>Aviatrix Controller</title>"

      - type: status
        status:
          - 200
```

### PR DESCRIPTION
**Pull request by RamanaReddy0M**
## Proposed changes

- closes  #5247

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: pkg/templates/templates.go [hunk 1]
```diff
@@ -326,6 +326,10 @@ func (template *Template) UnmarshalYAML(unmarshal func(interface{}) error) error
 	}
 	*template = Template(*alias)
 
+	if !ReTemplateID.MatchString(template.ID) {
```
Comment (dogancanbakir) [inline pkg/templates/templates.go:329]: We should consider adding checks for other mandatory fields as well. See parser_validate.go:validateTemplateMandatoryFields

**Review by dogancanbakir — APPROVED** [review]

**Review by dogancanbakir — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]
