### PR TITLE
fix: enable all template types for template list/display

### LINKED ISSUE #6644: Nuclei shows incorrect total template count when filtering by author
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Current Behavior

Running `nuclei -author DhiyaneshDK -tl -silent -code -dast | wc -l` returns an incorrect total (1753). The engine is not reporting the right number of templates for the author.

Image

### Expected Behavior

The total templates for DhiyaneshDK should be around 1925

Image

### Steps To Reproduce

```
pwnmachine@MacBook-Pro-88 Downloads % nuclei -author DhiyaneshDK -tl -silent -code -dast | wc -l
    1753
pwnmachine@MacBook-Pro-88 Downloads % 
```

### PR DESCRIPTION
**Pull request by dwisiswant0**
## Proposed changes

fix(runner): enable all template types for template list/display

When using `-tl` or `-td`, explicitly enable all
template types (`code`, `file`, `self-contained`,
`global-matchers`, `headless`, `dast`) to ensure
all templates are listed w/o requiring extra flags.

Fixes #6644.

## Checklist

- [x] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [x] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Summary by CodeRabbit

* **New Features**
  * Templates now declare explicit capability requirements and expose richer per-protocol predicates and helpers for enablement and fuzzing detection.
  * Request types add a HasFuzzing indicator.

* **Bug Fixes**
  * Duplicate templates are detected and skipped earlier to prevent repeated entries.

* **Chores**
  * Removed prior universal template enabling and introduced centralized gating; deprecated some legacy helpers.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: pkg/catalog/loader/loader.go [hunk 1]
```diff
@@ -435,15 +435,15 @@ func (store *Store) LoadTemplatesOnlyMetadata() error {
 	for templatePath := range validPaths {
 		template, _, _ := templatesCache.Has(templatePath)
 
-		if len(template.RequestsHeadless) > 0 && !store.config.ExecutorOptions.Options.Headless {
+		if len(template.RequestsHeadless) > 0 && !store.config.ExecutorOptions.Options.Headless && !store.config.ExecutorOptions.Options.TemplateList && !store.config.ExecutorOptions.Options.TemplateDisplay {
```
Comment (Mzack9999) [inline pkg/catalog/loader/loader.go]: maybe we can replace `store.config.ExecutorOptions.Options.Headless` with something like `store.config.ExecutorOptions.Options.Headless()` and have the logic inside the function?

```go
func (...) Headless() bool {
return ...Headless && !TemplateList && !TemplateDisplay
}
```

And same for the other option. What do you think?

Comment (dwisiswant0) [reply pkg/catalog/loader/loader.go]: Good call.

On top of that, I've been considering deprecating those types as well, mainly to bring them in line with the rest of our naming conventions, which follow the `EnableXTemplates` pattern.

Comment (dwisiswant0) [reply pkg/catalog/loader/loader.go]: > maybe we can replace `store.config.ExecutorOptions.Options.Headless` with something like `store.config.ExecutorOptions.Options.Headless()` [...]

I think that's probably going to end up conflicting, at least unless we:

> [...] considering deprecating those types [...]

and migrate the existing type names.

But, I think I have a cleaner way to handle this that avoids the mess.

**Comment by dwisiswant0** [comment]
Drafting. I'll do more cleanup.

**Comment by dwisiswant0** [comment]
tbh I think we've reached the stage where having a GLOSARRY would help a lot. We should probably start drafting one so everyone stays on the same page.

File: internal/runner/runner.go [hunk 2]
```diff
@@ -125,14 +125,6 @@ func New(options *types.Options) (*Runner, error) {
...
 		}
 
-		// if template list or template display is enabled, enable all templates
-		if options.TemplateList || options.TemplateDisplay {
-			options.EnableCodeTemplates = true
-			options.EnableFileTemplates = true
-			options.EnableSelfContainedTemplates = true
-			options.EnableGlobalMatchersTemplates = true
-		}
-
```
Comment (dwisiswant0) [inline internal/runner/runner.go:135]: Introduced in #6343. Removed, since mutating global opts in the runner could affects the entire engine state (UB).

File: pkg/templates/templates_utils.go [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+// HasRequest returns true if the given requests slice is non-empty.
+//
+// If min is provided, it checks for at least min requests.
+func HasRequest[T protocols.Request](requests []T, min ...int) bool {
+	if len(min) > 0 {
+		return len(requests) > min[0]
+	}
+
+	return len(requests) > 0
+}
```
[the remark this answers is not in the document]
Comment (dwisiswant0) [reply pkg/templates/templates_utils.go:14]: aight my bad

File: pkg/catalog/loader/loader.go [hunk 4]
```diff
@@ -663,22 +681,24 @@ func (store *Store) LoadTemplatesWithTags(templatesList, tags []string) []*templ
...
+	if typesOpts.ExecutionId == "" {
+		typesOpts.ExecutionId = xid.New().String()
 	}
 
-	dialers := protocolstate.GetDialersWithId(store.config.ExecutorOptions.Options.ExecutionId)
+	dialers := protocolstate.GetDialersWithId(typesOpts.ExecutionId)
 	if dialers == nil {
-		panic("dialers with executionId " + store.config.ExecutorOptions.Options.ExecutionId + " not found")
+		panic("dialers with executionId " + typesOpts.ExecutionId + " not found")
 	}
```
[the remark this answers is not in the document]
Comment (dwisiswant0) [reply pkg/catalog/loader/loader.go:703]: you should create seperate issue for that

[the remark this answers is not in the document]
Comment (dwisiswant0) [reply pkg/catalog/loader/loader.go:703]: go ahead
