### PR TITLE
Use httpx as library for http probing

### LINKED ISSUE #3241: Nuclei getting stuck when probing
### Nuclei version:
`dev`, `main`

### Current Behavior:
```console
echo 103.149.249.23:8443 | nuclei -id tech-detect

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.8

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.8 (latest)
[INF] Using Nuclei Templates 9.3.5 (latest)
[INF] Templates added in last update: 61
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[INF] Running httpx on input host
```

### Expected Behavior:

```console
echo 103.149.249.23:8443 | nuclei -id tech-detect

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.8

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.8 (latest)
[INF] Using Nuclei Templates 9.3.5 (latest)
[INF] Templates added in last update: 61
[INF] Templates loaded for scan: 1
[INF] Targets loaded for scan: 1
[tech-detect:nginx] [http] [info] http://103.149.249.23:8443
```

### Steps To Reproduce:
```
echo 103.149.249.23:8443 | nuclei -id tech-detect
```

### Anything else:
works as expected when running with httpx directly.

```
echo 103.149.249.23:8443 | httpx -silent

http://103.149.249.23:8443
```

### PR DESCRIPTION
**Pull request by Ice3man543**
## Proposed changes

Closes #3241

## Checklist

- [ ] Pull request is created against the [dev](https://github.com/projectdiscovery/nuclei/tree/dev) branch
- [ ] All checks passed (lint, unit/integration/regression tests etc.) with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: v2/internal/runner/inputs.go [hunk 1]
```diff
@@ -63,28 +67,22 @@ func (r *Runner) initializeTemplatesHTTPInput() (*hybrid.HybridMap, error) {
...
 
 // probeURL probes the scheme for a URL. first HTTPS is tried
 // and if any errors occur http is tried. If none succeeds, probing
 // is abandoned for such URLs.
-func probeURL(input string, httpclient *retryablehttp.Client) string {
+func probeURL(input string, httpxclient *httpx.HTTPX) string {
 	for _, scheme := range httpSchemes {
 		formedURL := fmt.Sprintf("%s://%s", scheme, input)
-		req, err := retryablehttp.NewRequest(http.MethodGet, formedURL, nil)
+		req, err := httpxclient.NewRequest(http.MethodGet, formedURL)
```
Comment (Mzack9999) [inline v2/internal/runner/inputs.go:79]: What do you think about using `HEAD` as we need to check if there is a web server (and skip body elaboration)?

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
proposing http method change

**Review by Mzack9999 — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]
